### ISSUE TITLE
 Kubedns authentication error

### ISSUE THREAD

**Issue by moonek** [kelseyhightower/kubernetes-the-hard-way#175]
I completed the installation of k8s according to this guide.
Finally, the only thing left to do is to deploy kubedns.

I proceeded in this way.
https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/09-dns-addon.md

However, the following error is repeated and kubedns is not running normally.

#kubectl get po --namespace=kube-system
NAME                       READY     STATUS             RESTARTS   AGE
kube-dns-321336704-7lj9h   2/4       CrashLoopBackOff   22         52m

#kubectl logs kube-dns-321336704-7lj9h -c kubedns --namespace=kube-system
(skip)
E0607 08:25:19.521958       1 reflector.go:199] pkg/dns/dns.go:148: Failed to list *api.Service: the server has asked for the client to provide credentials (get services)
E0607 08:25:19.523128       1 reflector.go:199] pkg/dns/dns.go:145: Failed to list *api.Endpoints: the server has asked for the client to provide credentials (get endpoints)
E0607 08:25:19.531436       1 reflector.go:199] pkg/dns/config/sync.go:114: Failed to list *api.ConfigMap: the server has asked for the client to provide credentials (get configmaps)
E0607 08:25:20.525202       1 reflector.go:199] pkg/dns/dns.go:148: Failed to list *api.Service: the server has asked for the client to provide credentials (get services)
E0607 08:25:20.526047       1 reflector.go:199] pkg/dns/dns.go:145: Failed to list *api.Endpoints: the server has asked for the client to provide credentials (get endpoints)
E0607 08:25:20.533398       1 reflector.go:199] pkg/dns/config/sync.go:114: Failed to list *api.ConfigMap: the server has asked for the client to provide credentials (get configmaps)
E0607 08:25:21.527819       1 reflector.go:199] pkg/dns/dns.go:148: Failed to list *api.Service: the server has asked for the client to provide credentials (get services)
E0607 08:25:21.528840       1 reflector.go:199] pkg/dns/dns.go:145: Failed to list *api.Endpoints: the server has asked for the client to provide credentials (get endpoints)
E0607 08:25:21.535500       1 reflector.go:199] pkg/dns/config/sync.go:114: Failed to list *api.ConfigMap: the server has asked for the client to provide credentials (get configmaps)
E0607 08:25:22.530925       1 reflector.go:199] pkg/dns/dns.go:148: Failed to list *api.Service: the server has asked for the client to provide credentials (get services)
E0607 08:25:22.532338       1 reflector.go:199] pkg/dns/dns.go:145: Failed to list *api.Endpoints: the server has asked for the client to provide credentials (get endpoints)
E0607 08:25:22.538358       1 reflector.go:199] pkg/dns/config/sync.go:114: Failed to list *api.ConfigMap: the server has asked for the client to provide credentials (get configmaps)

**Comment by githubixx** [comment]
@moonek Had the same problem. A quick workaround to get things going and which worked for me is to use the following arguments for the `kubedns` container:

```
        args:
        - --domain=cluster.local.
        - --dns-port=10053
        - --kube-master-url=http://xxx.xxx.xxx.xxx:8080
        - --v=2
```
Replace `xxx.xxx.xxx.xxx` with the host IP where the API server runs. Port 8080 is of course the insecure port of the API server (if you haven't changed it). So no secure traffic. That's maybe ok for a test system or in a private network but far from perfect.

I also tried a different (secure) variant with the following arguments to `kubedns` container:

```
        args:
        - --domain=cluster.local.
        - --dns-port=10053
        - --kubecfg-file=/var/lib/kubernetes/kubedns.conf
        - --v=2
...
          volumeMounts:
          - mountPath: /var/lib/kubernetes
            name: ssl-certs-kubernetes
            readOnly: true
```

For this to work you need additionally:

````
...
      dnsPolicy: Default  # Don't use cluster DNS.
      volumes:
      - hostPath:
          path: /var/lib/kubernetes
        name: ssl-certs-kubernetes
```

And on every worker node a file `/var/lib/kubernetes/kubedns.conf` with the following content:

````
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /var/lib/kubernetes/ca-k8s-apiserver.pem
    server: https://xxx.xxx.xxx.xxx:6443
  name: default-cluster
contexts:
- context:
    cluster: default-cluster
    user: default-admin
  name: default-system
current-context: default-system
kind: Config
preferences: {}
users:
- name: default-admin
  user:
    client-certificate: /var/lib/kubernetes/cert-k8s-apiserver.pem
    client-key: /var/lib/kubernetes/ca-k8s-apiserver-key.pem
```
Sadly I couldn't get this working until now.
