### ISSUE TITLE
Error from server: the server has asked for the client to provide credentials

### ISSUE THREAD

**Issue by sgonzalezO** [kelseyhightower/kubernetes-the-hard-way#21]
Don't know what I'm doing wrong but I can't use kubectl.

More info: cat .kube/config
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: 
    MYCERT (ca.pem)
    server: https://23.251.140.185:6443
  name: kubernetes-the-hard-way
contexts:
- context:
    cluster: kubernetes-the-hard-way
    user: admin
  name: default-context
current-context: default-context
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: MYPASSWORD
```

Another thing, I have created a new firewall rule so I can access my cluster outside my project.

Thanks.
