### ISSUE TITLE
Permission issues with nodes 

### ISSUE THREAD

**Issue by fauzigo** [kelseyhightower/kubernetes-the-hard-way#303]
Hi All,

I followed the documents shared here (which by the way, are awesome) a few times, and I keep coming across the same issue over and over.

In part 5 [05-kubernetes-configuration-files.md], you set the configuration files for the nodes and the proxy, in which you set the user names to `system:node:worker-[0-2]` and `kube-proxy` respectively.

In part 8 [08-bootstrapping-kubernetes-controllers.md] you set RBAC for Kubelet Authorization. 

However, I was getting errors in the logs regarding access permissions:

On the controllers:
`Jan 25 18:50:47 controller-0 kube-apiserver[1930]: I0125 18:50:47.151666    1930 rbac.go:116] RBAC DENY: user "system:node:worker-0" groups ["system:nodes" "Organization" "system:authenticated"] cannot "list" resource "endpoints" cluster-wide`

On the workers:
`Jan 25 18:50:30 worker-0 kube-proxy[2057]: I0125 18:50:30.492388    2057 proxier.go:984] Not syncing iptables until Services and Endpoints have been received from master
Jan 25 18:50:31worker-0 kube-proxy[2057]: E0125 18:50:31.103252    2057 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:85: Failed to list *core.Endpoints: endpoints is forbidden: User "worker-0" cannot list endpoints at the cluster scope`

Permissions in the `ClusterRole` `system:kube-apiserver-to-kubelet` never mentioned endpoints, so I decided to add the following:

```yaml
cat <<EOF | kubectl apply -f -
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:kube-apiserver-to-kubelet
rules:
  - apiGroups:
      - ""
    resources:
      - nodes/proxy
      - nodes/stats
      - nodes/log
      - nodes/spec
      - nodes/metrics
      - endpoints
    verbs:
      - "*"
EOF
```

But the issue persisted, then I noticed that the user `kubernetes` is neither set for the proxy nor the nodes, but that's what's used in the `ClusterRoleBinding`. Given the fact that nodes belong to the group `system:nodes`, I did the following for the binding:

```yaml
cat <<EOF | kubectl apply -f -
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: system:kube-apiserver
  namespace: ""
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-apiserver-to-kubelet
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:nodes
EOF
```

And things started working flawlessly. Perhaps * (verbs) for endpoints resources are too permissive for the nodes, not sure. We can try playing a little more with this and maybe using only list instead, but as for now, the errors stopped. 

I also faced issues in [Getting a bunch of 404 when Initializers option is activated](https://github.com/kelseyhightower/kubernetes-the-hard-way/issues/276), but what @nmaupu suggested fixed it for me.

I used [Remove default binding of system:node role to system:nodes group](https://github.com/kubernetes/kubernetes/pull/49638) and [Using RBAC Authorization](https://kubernetes.io/docs/admin/authorization/rbac/#referring-to-resources) as help to enlighten my path.

I hope this is helpful.

And thanks.

**Comment by fauzigo** [comment]
This seems suffice as well:

```yaml
cat <<EOF | kubectl apply -f -
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:kube-apiserver-to-kubelet
rules:
  - apiGroups:
      - ""
    resources:
      - nodes/proxy
      - nodes/stats
      - nodes/log
      - nodes/spec
      - nodes/metrics
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - "list"
EOF
```
