### ISSUE TITLE
kubelet->api-server "error: failed to run Kubelet: No authentication method configured"

### ISSUE THREAD

**Issue by jforman** [kelseyhightower/kubernetes-the-hard-way#310]
I've been following the guide and am on the step in 09 where I start the worker services [1]. But from one of my worker nodes, I'm seeing the following error about missing authentication methods.

Feb 03 01:04:19 coreA-worker0.foo.domain.net kubelet[19555]: error: failed to run Kubelet: No authentication method configured
Feb 03 01:04:19 coreA-worker0.foo.domain.net systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE
Feb 03 01:04:19 coreA-worker0.foo.domain.net systemd[1]: kubelet.service: Failed with result 'exit-code'.

I looked at my kubeconfig but it looks correct, not missing any context specifications.

```
core@coreA-worker0 ~ $ systemctl cat kubelet.service
# /etc/systemd/system/kubelet.service
[Unit]
Description=Kubernetes Kubelet
Documentation=https://github.com/kubernetes/kubernetes

[Service]
ExecStart=/opt/kubernetes/bin/kubelet \
  --allow-privileged=true \
  --anonymous-auth=false \\
  --authorization-mode=Webhook \
  --client-ca-file=/var/lib/kubernetes/ca.pem \
  --cloud-provider= \
  --cluster-dns=10.122.0.10 \
  --cluster-domain=cluster.local \
  --container-runtime=rkt \
  --image-pull-progress-deadline=2m \
  --kubeconfig=/var/lib/kubelet/kubeconfig \
  --network-plugin=cni \
  --pod-cidr=10.123.101.0/24 \
  --register-node=true \
  --runtime-request-timeout=15m \
  --tls-cert-file=/var/lib/kubelet/coreA-worker0.foo.domain.net.pem \
  --tls-private-key-file=/var/lib/kubelet/coreA-worker0.foo.domain.net-key.pem \
  --v=4
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
```

```
core@coreA-worker0 ~ $ sudo cat /var/lib/kubelet/kubeconfig
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: foooooooooooo
    server: https://10.10.0.119:6443
  name: coreA
contexts:
- context:
    cluster: coreA
    user: system:node:coreA-worker0.foo.domain.net
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: system:node:coreA-worker0.foo.domain.net
  user:
    as-user-extra: {}
    client-certificate-data: fooooo
    client-key-data: foooo
```

Various client key and cert data elided to protect the innocent.

Various infrastructure stats:
* Operating System: CoreOS Beta Channel running as VMs 
* 3 controller nodes, 5 worker nodes.

What am I missing here? Any help is greatly appreciated!

1: https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/09-bootstrapping-kubernetes-workers.md#start-the-worker-services
