### ISSUE TITLE
kubelet services is not starting 

### ISSUE THREAD

**Issue by kylix3511** [kelseyhightower/kubernetes-the-hard-way#399]
Hi There, 

I tried this kubenetes-the-hard-way for learning purpose .... 

When Bootstrapping the Kubernetes Worker Nodes and Kubelets configuration and starting ... I got this error :
 
```
_ubuntu@worker1:~\$  sudo systemctl status kubelet 
kubelet.service - Kubernetes Kubelet
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: activating (auto-restart) (Result: exit-code) since Wed 2018-10-17 12:06:49 PDT; 1s ago
     Docs: https://github.com/kubernetes/kubernetes
  Process: 13724 ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_SYSTEM_PODS_ARGS $KUBELET_NETWORK_ARGS $KUBELET_DNS_ARGS $KUBELET_AUTHZ_ARGS $KUBELET_CADVISOR_ARGS $KUBELET_CERTIFICATE_ARGS $KUBELET_EXTRA_ARGS (code=exited, status=1/FAILURE)
 Main PID: 13724 (code=exited, status=1/FAILURE)
ubuntu@worker1:~\$_  
```

```
ubuntu@worker1:~\$ sudo cat /var/lib/kubelet/kubeconfig
[sudo] password for ubuntu: 
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: 
<deleted>
    server: https://10.1.1.77:6443
  name: kubernetes-the-hard-way
contexts:
- context:
    cluster: kubernetes-the-hard-way
    user: system:node:worker1.mylabserver.com
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: system:node:worker1.mylabserver.com
  user:
    client-certificate-data: 
<deleted>
    client-key-data: 
<deleted>
ubuntu@worker1:~\$
```

Any idea ? Whats the issue ? what did I missed or forgetted ?
