### ISSUE TITLE
kube-scheduler config file api version

### ISSUE THREAD

**Issue by cgcgbcbc** [kelseyhightower/kubernetes-the-hard-way#427]
the api version `componentconfig/v1alpha1` has been deprecated since 1.9 is not supported in 1.13, which should be changed to `apiVersion: kubescheduler.config.k8s.io/v1alpha1`

**Comment by jasperroel** [comment]
Just here to correctly indent the fix:

```
cat <<EOF | sudo tee /etc/kubernetes/config/kube-scheduler.yaml
apiVersion: kubescheduler.config.k8s.io/v1alpha1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: "/var/lib/kubernetes/kube-scheduler.kubeconfig"
leaderElection:
  leaderElect: true
EOF
```

Then verify with
`systemctl status kube-scheduler`
and see that the status has moved to `Active: active (running)` (it auto-restarts every 5 seconds).
Make sure to do this on all (3) controllers.

Run
`kubectl get componentstatuses --kubeconfig admin.kubeconfig`
to verify that the `scheduler` is reporting **Healthy** as well.

**Comment by ioanc** [comment]
> as per [https://github.com/kubernetes/kubernetes/pull/66916](url) , using a config file is still alpha.
> changed the service file to use the same options as in the config file

[Unit]
Description=Kubernetes Scheduler
Documentation=https://github.com/kubernetes/kubernetes

[Service]
ExecStart=/usr/local/bin/kube-scheduler \
  --leader-elect=true \
  --kubeconfig=/var/lib/kubernetes/kube-scheduler.kubeconfig \
  --v=2
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target

**Comment by kelseyhightower** [comment]
Fixed on master.

**Comment by JulienBreux** [comment]
For the future readers, the new version is currently: `kubescheduler.config.k8s.io/v1beta1`

Example:
```yaml
apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: "/var/lib/kubernetes/kube-scheduler.kubeconfig"
leaderElection:
  leaderElect: true
```

/ref https://kubernetes.io/docs/reference/scheduling/config/
