### ISSUE TITLE
Kube-scheduler config incorrect for K8S 1.19.x

### ISSUE THREAD

**Issue by recrudesce** [kelseyhightower/kubernetes-the-hard-way#596]
v1alpha1 has been deprecated, therefore you need to use v1beta1 if you're using K8S 1.19.x in kube-scheduler.yaml

```
apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: "/var/lib/kubernetes/kube-scheduler.kubeconfig"
leaderElection:
  leaderElect: true
```
