### ISSUE TITLE
No encryption-config.yaml 

### ISSUE THREAD

**Issue by vaibhav17octo** [kelseyhightower/kubernetes-the-hard-way#787]
In the encryption key section. We have to create an encryption file from the following file by replacing the environment variable.
However, the file is not present in the repository:
configs/encryption-config.yaml

**Comment by martopad** [comment]
As a workaround, I skipped that step and removed the --encryption-provider-config flags on the services files in units folder.

**Comment by nightbarron** [comment]
`apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: ${ENCRYPTION_KEY}
      - identity: {}`

I created this in configs/encryption-config.yaml, and it worked

**Comment by jimweller** [comment]
Thanks @nightbarron. Your file got me through the labs. I also needed an apiVersion.

```
apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: ${ENCRYPTION_KEY}
      - identity: {}
```
